In [1]:
pip install pdfplumber

Requirement already satisfied: pdfplumber in c:\users\admin\anaconda3\lib\site-packages (0.11.9)
Requirement already satisfied: pdfminer.six==20251230 in c:\users\admin\anaconda3\lib\site-packages (from pdfplumber) (20251230)
Requirement already satisfied: Pillow>=9.1 in c:\users\admin\anaconda3\lib\site-packages (from pdfplumber) (10.4.0)
Requirement already satisfied: pypdfium2>=4.18.0 in c:\users\admin\anaconda3\lib\site-packages (from pdfplumber) (5.6.0)
Requirement already satisfied: charset-normalizer>=2.0.0 in c:\users\admin\anaconda3\lib\site-packages (from pdfminer.six==20251230->pdfplumber) (3.3.2)
Requirement already satisfied: cryptography>=36.0.0 in c:\users\admin\anaconda3\lib\site-packages (from pdfminer.six==20251230->pdfplumber) (43.0.0)
Requirement already satisfied: cffi>=1.12 in c:\users\admin\anaconda3\lib\site-packages (from cryptography>=36.0.0->pdfminer.six==20251230->pdfplumber) (1.17.1)
Requirement already satisfied: pycparser in c:\users\admin\anaconda3\lib\site-packages (from cffi>=1.12->cryptography>=36.0.0->pdfminer.six==20251230->pdfplumber) (2.21)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

In [3]:
df=pd.read_excel("allsbe.xlsx", skiprows=8)
df.head(20)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Budget Estimates2026-2027,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,NaN,NaN,NaN,NaN,NaN,NaN,Revenue,Capital,NaN,Total,NaN,NaN,Page No
1,NaN,NaN,Ministry of Agriculture and Farmers Welfare,NaN,NaN,NaN,140416.57,112.21,NaN,140528.78,NaN,NaN,NaN
2,NaN,NaN,1.,Department of Agriculture and Farmers Welfare,NaN,NaN,130451.62,109.76,NaN,130561.38,NaN,NaN,1-6
3,NaN,NaN,2.,Department of Agricultural Research and Education,NaN,NaN,9964.95,2.45,NaN,9967.4,NaN,NaN,7-9
4,NaN,NaN,Department of Atomic Energy,NaN,NaN,NaN,14157.51,9966.41,NaN,24123.92,NaN,NaN,NaN
5,NaN,NaN,3.,Atomic Energy,NaN,NaN,14157.51,9966.41,NaN,24123.92,NaN,NaN,10-15
6,NaN,NaN,Ministry of AYUSH,NaN,NaN,NaN,4381.86,27.07,NaN,4408.93,NaN,NaN,NaN
7,NaN,NaN,4.,Ministry of Ayush,NaN,NaN,4381.86,27.07,NaN,4408.93,NaN,NaN,16-19
8,NaN,NaN,Ministry of Chemicals and Fertilisers,NaN,NaN,NaN,177049.76,11.71,NaN,177061.47,NaN,NaN,NaN
9,NaN,NaN,5.,Department of Chemicals and Petrochemicals,NaN,NaN,184.7,1.02,NaN,185.72,NaN,NaN,20-21
10,NaN,NaN,6.,Department of Fertilisers,NaN,NaN,170935.64,8.89,NaN,170944.53,NaN,NaN,22-24
11,NaN,NaN,7.,Department of Pharmaceuticals,NaN,NaN,5929.42,1.8,NaN,5931.22,NaN,NaN,25-28
12,NaN,NaN,Ministry of Civil Aviation,NaN,NaN,NaN,2057.87,45,NaN,2102.87,NaN,NaN,NaN
13,NaN,NaN,8.,Ministry of Civil Aviation,NaN,NaN,2057.87,45,NaN,2102.87,NaN,NaN,29-31
14,NaN,NaN,Ministry of Coal,NaN,NaN,NaN,3633.12,2.2,NaN,3635.32,NaN,NaN,NaN
15,NaN,NaN,9.,Ministry of Coal,NaN,NaN,3633.12,2.2,NaN,3635.32,NaN,NaN,32-33
16,NaN,NaN,Ministry of Commerce and Industry,NaN,NaN,NaN,12677.46,5166.44,NaN,17843.9,NaN,NaN,NaN
17,NaN,NaN,10.,Department of Commerce,NaN,NaN,5825.76,47.31,NaN,5873.07,NaN,NaN,34-37
18,NaN,NaN,11.,Department for Promotion of Industry and Inter...,NaN,NaN,6851.7,5119.13,NaN,11970.83,NaN,NaN,38-42
19,NaN,NaN,Ministry of Communications,NaN,NaN,NaN,53742.59,48524.43,NaN,102267.02,NaN,NaN,NaN

In [12]:
print(df.columns.tolist())
df.iloc[:5, :10]

['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', ' Budget Estimates2026-2027 ', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12']

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Budget Estimates2026-2027,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,NaN,NaN,NaN,NaN,NaN,NaN,Revenue,Capital,NaN,Total
1,NaN,NaN,Ministry of Agriculture and Farmers Welfare,NaN,NaN,NaN,140416.57,112.21,NaN,140528.78
2,NaN,NaN,1.,Department of Agriculture and Farmers Welfare,NaN,NaN,130451.62,109.76,NaN,130561.38
3,NaN,NaN,2.,Department of Agricultural Research and Education,NaN,NaN,9964.95,2.45,NaN,9967.4
4,NaN,NaN,Department of Atomic Energy,NaN,NaN,NaN,14157.51,9966.41,NaN,24123.92

In [14]:
df_clean=df[["Unnamed: 2", "Unnamed: 9"]]
df_clean.columns=["Ministry", "Total_Allocation"]
df_clean.head(20)

                                       Ministry Total_Allocation
0                                           NaN            Total
1   Ministry of Agriculture and Farmers Welfare        140528.78
2                                           1.         130561.38
3                                           2.            9967.4
4                   Department of Atomic Energy         24123.92
5                                           3.          24123.92
6                             Ministry of AYUSH          4408.93
7                                           4.           4408.93
8         Ministry of Chemicals and Fertilisers        177061.47
9                                           5.            185.72
10                                          6.         170944.53
11                                          7.           5931.22
12                   Ministry of Civil Aviation          2102.87
13                                          8.           2102.87
14                             Ministry of Coal          3635.32
15                                          9.           3635.32
16            Ministry of Commerce and Industry          17843.9
17                                         10.           5873.07
18                                         11.          11970.83
19                   Ministry of Communications        102267.02

In [24]:
df_clean=df_clean.dropna(subset=["Ministry", "Total_Allocation"])
df_clean.head(20)
df_clean=df_clean[~df_clean["Ministry"].str.match(r"v\d")]
df_clean.reset_index(drop=True, inplace=True)
df_clean.head(20)

                                       Ministry Total_Allocation
0   Ministry of Agriculture and Farmers Welfare        140528.78
1                                           1.         130561.38
2                                           2.            9967.4
3                   Department of Atomic Energy         24123.92
4                                           3.          24123.92
5                             Ministry of AYUSH          4408.93
6                                           4.           4408.93
7         Ministry of Chemicals and Fertilisers        177061.47
8                                           5.            185.72
9                                           6.         170944.53
10                                          7.           5931.22
11                   Ministry of Civil Aviation          2102.87
12                                          8.           2102.87
13                             Ministry of Coal          3635.32
14                                          9.           3635.32
15            Ministry of Commerce and Industry          17843.9
16                                         10.           5873.07
17                                         11.          11970.83
18                   Ministry of Communications        102267.02
19                                         12.          28276.08

In [22]:
df_clean["Ministry"].iloc[1:5].tolist()

['1. ', '2. ', 'Department of Atomic Energy', '3. ']

In [26]:
df_clean=df_clean[df_clean["Ministry"].str.strip().str.len()>4]
df_clean.reset_index(drop=True, inplace=True)
df_clean.head(20)

                                             Ministry Total_Allocation
0         Ministry of Agriculture and Farmers Welfare        140528.78
1                         Department of Atomic Energy         24123.92
2                                   Ministry of AYUSH          4408.93
3               Ministry of Chemicals and Fertilisers        177061.47
4                          Ministry of Civil Aviation          2102.87
5                                    Ministry of Coal          3635.32
6                   Ministry of Commerce and Industry          17843.9
7                          Ministry of Communications        102267.02
8   Ministry of Consumer Affairs, Food and Public ...        239521.37
9                             Ministry of Cooperation          1744.74
10                      Ministry of Corporate Affairs          5561.86
11                                Ministry of Culture          3416.63
12                                Ministry of Defence        784678.28
13   Ministry of Development  of North Eastern Region           6812.3
14                         Ministry of Earth Sciences          3789.23
15                              Ministry of Education        139289.48
16  Ministry of Electronics and Information Techno...         21632.96
17  Ministry of Environment, Forests and Climate C...          3759.46
18                       Ministry of External Affairs         22118.97
19                                Ministry of Finance       1972509.48

In [28]:
print(df_clean.shape)

(56, 2)

In [30]:
df_sorted=df_clean.sort_values("Total_Allocation", ascending=False)
df_sorted.head(10)

                                             Ministry Total_Allocation
19                                Ministry of Finance       1972509.48
12                                Ministry of Defence        784678.28
43            Ministry of Road Transport and Highways         309875.3
42                               Ministry of Railways        281377.32
24                           Ministry of Home Affairs        255233.53
8   Ministry of Consumer Affairs, Food and Public ...        239521.37
44                      Ministry of Rural Development        197023.14
3               Ministry of Chemicals and Fertilisers        177061.47
0         Ministry of Agriculture and Farmers Welfare        140528.78
15                              Ministry of Education        139289.48

In [32]:
df_sorted.to_csv("budget_clean.csv", index=False)